
name: Build and Push to ACR

on:
  workflow_dispatch: # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: netflix
      IMAGE_TAG: v1
      ACR_NAME: aksregiter
      ACR_LOGIN_SERVER: aksregiter.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 4e13f5bc-0f8d-4f59-8af5-6f5f7efa1f24
          tenant-id: d62d1853-842b-4d22-b4c5-4fa00b2bcec9
          subscription-id: 09d55635-2a09-4af6-9e93-6bb44383a7aa

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
